repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: name-tests-test
    args: ["--unittest"]
  - id: check-case-conflict

- repo: https://github.com/pycqa/flake8
  rev: '5.0.4'
  hooks:
  - id: flake8
    args:
    # A bug with Flake8 throwing "F821: undefined name `name`"
    - --extend-ignore=F821

- repo: https://github.com/asottile/add-trailing-comma
  rev: v2.2.3
  hooks:
  - id: add-trailing-comma

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.6
  hooks:
    - id: codespell
      exclude: "api/config/|manifests/api/profanity-list.yaml"

- repo: local
  hooks:
    - id: tests
      name: run tests
      entry: python3 -m unittest discover
      language: python
      'types': [python]
      additional_dependencies:
      - "fastapi[standard]"
      - "transformers"
      - "scikit-learn"
      - "pandas"
      - "langchain_ollama"
      pass_filenames: false
      stages: [pre-commit]
