apiVersion: v1
kind: Service
metadata:
  name: yggdrasil-api
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      # nodePort: 38080 # To expose the port on real K8s environments (other than Kind)
  type: NodePort
  selector:
    app: yggdrasil-api
