apiVersion: v1
kind: Service
metadata:
  name: ollama
spec:
  ports:
    - protocol: TCP
      port: 11434
      targetPort: 11434
      # nodePort: 31434 # To expose the port on real K8s environments (other than Kind)
  type: NodePort
  selector:
    app: ollama
