kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.31.1
  extraPortMappings:
  - containerPort: 11434
    hostPort: 11434
    listenAddress: "127.0.0.1"
    protocol: TCP
  - containerPort: 8080
    hostPort: 8080
    listenAddress: "127.0.0.1"
    protocol: TCP
